#!/usr/bin/env bash

create_dummy() {
cat << EOF > $1/manifests/argocd_dummy_trigger.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-dummy-trigger-fastapitutorial
  namespace: fastapi
data:
  foo: "$(date)"
EOF

git add $1/manifests/argocd_dummy_trigger.yaml
}