#!/bin/bash
echo "testing post-pre-commit"

# Run some tools prior to pre-commit to avoid potential problems.
black src/

# As per https://stackoverflow.com/questions/67793193/cowardly-refusing-to-install-hooks-with-core-hookspath-set:
# The problem with global core.hooksPath configured is that the global hooks (in $HOME/.git/hooks/)
# override the local ones in each repository. So, it is important to put some explicit delagation to
# your $HOME/.git/hooks/pre-commit. I placed this on top of the file (after #! line, ofc.)

# Run local pre-commit hook if it exists
# if [ -e ./.git/hooks/pre-commit ]; then
#   if ! (./.git/hooks/pre-commit "$@"); then
#     exit 1;
#   fi
# fi
# pre-commit

# Taken from: https://github.com/gwright99/aws_lambda/blob/main/.githooks/pre-commit
# if [[ $(git diff --cached --quiet --diff-filter=ACMR -- "app/*"; echo $?) == 1 ]]; then
if [[ $(git diff --cached --quiet --diff-filter=ACMR -- "src/*"; echo $?) == 1 ]]; then

  echo "Found modified app files."

  # See notes above for explanation of logic and design
  # git diff --cached --name-only --diff-filter=ACMR -- "app/*" | \
  git diff --cached --name-only --diff-filter=ACMR -- "src/*" | \
  xargs -I % sh -c \
     'echo "$PWD";
      . "$PWD/.githooks/create_dummy";
      export APP_PATH="$PWD";
      env | grep APP_PATH;
      create_dummy $APP_PATH;'
fi
