# https://pre-commit.com/
exclude: '^$'
fail_fast: false

repos:
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        language_version: python3.10

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        types: [python]
        # Rely on `setup.cfg` for flake8 rules instead of inline
        # args: [--max-line-length=88]
        #files: ^my_appname/|^test_suite_name/

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    # All hooks: https://github.com/pre-commit/pre-commit-hooks
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    # -   id: check-json          # Can't handle JSON with comments
