apiVersion: v1
kind: ConfigMap
metadata:
  name: tutorial-purgescript
  namespace: fastapi
data:
  purge.sh: |
    apt update && apt install -y jq

    APISERVER=https://kubernetes.default.svc
    SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
    NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
    TOKEN=$(cat ${SERVICEACCOUNT}/token)
    CACERT=${SERVICEACCOUNT}/ca.crt

    sleep 5
    jq --version

    PODNAME=$(curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/namespaces/$NAMESPACE/pods | jq '.items[].metadata.name' | echo $(grep -e "fastapi-tutorial") | xargs)
    sleep 5
    echo $PODNAME
    curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X DELETE ${APISERVER}/api/v1/namespaces/$NAMESPACE/pods/$PODNAME
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: delete-tutorial
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  namespace: fastapi
spec:
  template:
    spec:
      serviceAccountName: delete-tutorial
      containers:
      - name: delete-pod  # Cant allow collision with crude grep in CM.
        image: nginx:latest
        command: ["/bin/bash"]
        args: ["-c", "/tmp/purge/purge.sh"]
        volumeMounts:
          - name: tutorial-purgescript
            mountPath: /tmp/purge/
      volumes:
        - name: tutorial-purgescript
          configMap:
            defaultMode: 0777   # To defeat ReadOnly
            name: tutorial-purgescript
            items:
              - key: purge.sh
                path: purge.sh
      restartPolicy: Never
---
    