apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: delete-fastapi-tutorial
  namespace: fastapi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fastapi
  name: delete-fastapi-tutorial
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: delete-fastapi-tutorial
  namespace: fastapi
subjects:
- kind: ServiceAccount
  name: delete-fastapi-tutorial
  namespace: fastapi
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: delete-fastapi-tutorial # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io