on: 
  # push:
  #   branches: ["main"]
  
  pull_request:
    branches: ["master", "main"]

jobs:

  check_commit:
    runs-on: ubuntu-latest
    steps:

      - name: Dump GitHub context
        id: ghcontext
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Get head ref
        uses: actions/checkout@v4
        with:
          # Get the latest commit on the branch to merge
          ref: ${{ github.event.pull_request.head.ref }}

      - name: check if message contain keywords ace scopeid
        id: check_commit
        run: |
          # Get the log message of the last commit in branch
          message=$(git log -1 --pretty=format:'%s')

          # Regex search for [doc] or [skip-tests]
          re="\[(doc|skip-tests)\]"
          if [[ $message =~ $re ]]; then
            # This is deprecated. Should be different.
            # echo "::set-output name=match::true"
            echo "match=true" >> $GITHUB_OUTPUT
            echo "$message -> Match is true"
          else
            echo "$message -> Match is false"
          fi
    outputs:
      match: ${{ steps.check_commit.outputs.match }}

  test:
    needs: check_commit
    if: ${{ needs.check_commit.outputs.match != 'true' }}
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: test stuffs 
        run: echo "Simulating tests"
